<ul>
	<li><a <?=$this->view->getControllerName() == 'index' ? 'class="active"' : ''?> href="/">Home</a></li>
	<li><a <?=$this->view->getControllerName() == 'about' ? 'class="active"' : ''?> href="/about">About</a></li>
	<li><a <?=$this->view->getControllerName() == 'contact' ? 'class="active"' : ''?> href="/contact">Contact Us</a></li>
	<li><a <?=$this->view->getControllerName() == 'gallery' ? 'class="active"' : ''?> href="/gallery">Gallery</a></li>
	<li><a <?=$this->view->getControllerName() == 'products' ? 'class="active"' : ''?> href="/products">Products</a></li>
</ul>
