<h2><?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('gallery')->title);?></h2>
<p><?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('gallery')->text);?></p>

<ul id="box-container" style="width:40%">
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-1.jpg" class="swipebox" title="Fog">
			<img src="http://swipebox.csag.co/images/image-1.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-2.jpg" class="swipebox" title="City">
			<img src="http://swipebox.csag.co/images/image-2.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-3.jpg" class="swipebox" title="Street">
			<img src="http://swipebox.csag.co/images/image-3.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-4.jpg" class="swipebox" title="Mustache Guy">
			<img src="http://swipebox.csag.co/images/image-4.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-1.jpg" class="swipebox" title="Fog">
			<img src="http://swipebox.csag.co/images/image-1.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-2.jpg" class="swipebox" title="City">
			<img src="http://swipebox.csag.co/images/image-2.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-3.jpg" class="swipebox" title="Street">
			<img src="http://swipebox.csag.co/images/image-3.jpg" alt="image">
		</a>
	</li>
	<li class="box">
		<a href="http://swipebox.csag.co/images/image-4.jpg" class="swipebox" title="Mustache Guy">
			<img src="http://swipebox.csag.co/images/image-4.jpg" alt="image">
		</a>
	</li>
</ul>
