<h2><?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('contact')->title);?></h2>
<p><?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('contact')->text);?></p>

<?=Phalcon\Tag::form(array($this->view->form->getAction(), 'onsubmit' => 'return validateContactForm();', 'name' => 'contact')) ?>

<table>
	<tr>
		<td><label for="<?=$form->get('username')->getName()?>"><?=$form->get('username')->getLabel()?>:</label></td>
		<td style="width: 100%">
<?=$form->render('username') ?>
			<span>
<?php
	if (isset($this->view->getVar('errors')[$form->get('username')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('username')->getName()]);
	}
?>
			</span>
		</td>
	</tr>
	<tr>
		<td><label for="<?=$form->get('email')->getName()?>"><?=$form->get('email')->getLabel()?>:</label></td>
		<td style="width: 100%">
<?=$form->render('email') ?>
			<span>
<?php
	if (isset($this->view->getVar('errors')[$form->get('email')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('email')->getName()]);
	}
?>
			</span>
		</td>
	</tr>
	<tr>
		<td><label for="<?=$form->get('subject')->getName()?>"><?=$form->get('subject')->getLabel()?>:</label></td>
		<td style="width: 100%">
<?=$form->render('subject') ?>
			<span>
<?php
	if (isset($this->view->getVar('errors')[$form->get('subject')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('subject')->getName()]);
	}
?>
			</span>
		</td>
	</tr>
	<tr>
		<td><label for="<?=$form->get('text')->getName()?>"><?=$form->get('text')->getLabel()?>:</label></td>
		<td style="width: 100%">
<?=$form->render('text') ?>
			<span>
<?php
	if (isset($this->view->getVar('errors')[$form->get('text')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('text')->getName()]);
	}
?>
			</span>
		</td>
	</tr>
	<tr>
		<td><label>Captcha:</label></td>
		<td style="width: 100%">
<?=$this->view->captcha->getHtml()?>
<?if ($this->view->captcha->getError()) {?>
		<span>
<?=$this->view->captcha->getError()?>
		</span>
<? } ?>
		</td>
	</tr>
	<tr>
		<td><?=$form->render('submit') ?></td>
	</tr>
</table>

<?=Phalcon\Tag::endForm ()?>
