<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Homework</title>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<?
echo Phalcon\Tag::stylesheetLink('css/main.css');
echo Phalcon\Tag::javascriptInclude('https://code.jquery.com/jquery.js', false);
echo Phalcon\Tag::javascriptInclude('js/main.js');
// attach gallery js and css only for gallery page
if ($this->view->getVar('gallery')) {
	echo Phalcon\Tag::stylesheetLink('css/gallery.css');
	echo Phalcon\Tag::javascriptInclude('//cdn.jsdelivr.net/jquery.swipebox/1.2.1/jquery.swipebox.min.js');
	echo Phalcon\Tag::stylesheetLink('//cdn.jsdelivr.net/jquery.swipebox/1.2.1/swipebox.css');
}
?>
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<section class="container">
			<header>
<?=$this->partial('partials/header')?>
			</header>
			<nav class="navbar">
<?=$this->partial('partials/navbar')?>
			</nav>
			<section>
<?=$this->getContent() ?>
			</section>
			<footer class="footer">
<?
echo $this->partial('partials/footer');
// display gallery js only on appropriate page
if ($this->view->getVar('gallery')){
?>
	<script type="text/javascript">
		// initialize gallery plugin
		;(function($){$('.swipebox').swipebox();})(jQuery);
	</script>
<? } ?>

			</footer>
		</section>
	</body>
</html>
